apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "go-server.fullname" . }}
  labels:
    {{- include "go-server.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- toYaml .Values.goserver | default "{}" | nindent 4 }}